- name: Clone lvm-mib tools
  git:
    repo: 'https://github.com/tobias-richter/lvm-mib.git'
    dest: /opt/lvm-mib
    version: master
  notify: restart snmpd

- name: Install sudo
  package:
    name: sudo

- name: give debian snmp user the appropriate sudo rights.
  blockinfile:
    path: /etc/sudoers.d/012_debian-snmp-lvm-mib
    create: yes
    block: |
      Debian-snmp ALL=(ALL) NOPASSWD: /sbin/vgs*, /sbin/lvs*

- name: Install mib file
  copy:
    src: /opt/lvm-mib/mibs/LVM-MIB.txt
    dest: /usr/share/snmp/mibs/
    remote_src: yes
  notify: restart snmpd



